#!/bin/sh

BASE_DIR=/opt/circonus
LOGCEP_DIR=$BASE_DIR/etc/logstream-cep
LOGCEP_BIN=$BASE_DIR/bin/logstream-cep
PIDFILE=$BASE_DIR/var/logstream-cep/logstream-cep.pid

case "$1" in
  start)
        echo "Starting logstream-cep"
        if [ -e "$PIDFILE" ]; then
            echo "logstream-cep already running with PID " `cat $PIDFILE`
        else
            cd $LOGCEP_DIR
            $LOGCEP_BIN -P $PIDFILE
        fi
        ;; 
  stop) 
        echo "Stopping logstream-cep"
        cat $PIDFILE | xargs kill
        if [ 0 = $? ]; then
            rm $PIDFILE
        else
            echo "Error stopping logstream-cep"
        fi
        ;; 
  restart) 
        echo "Restarting logstream-cep"
        cat $PIDFILE | xargs kill
        if [ 0 = $? ]; then
            cd $LOGCEP_DIR
            rm $PIDFILE
            $LOGCEP_BIN -P $PIDFILE
        fi
        ;; 
  *) 
        echo "Usage: logstream-cep {start|stop|restart}" >&2 
        exit 3 
        ;; 
esac
