#!/bin/sh
case "$1" in
  start)
        echo "Starting logstream-cep"
        if [ -e "/opt/circonus/var/logstream-cep/logstream-cep.pid" ]; then
            echo "logstream-cep already running with PID " `cat /opt/circonus/var/logstream-cep/logstream-cep.pid`
        else
            /opt/circonus/bin/logstream-cep -P /opt/circonus/var/logstream-cep/logstream-cep.pid
        fi
        ;; 
  stop) 
        echo "Stopping logstream-cep"
        cat /opt/circonus/var/logstream-cep/logstream-cep.pid | xargs kill
        if [ 0 = $? ]; then
            rm /opt/circonus/var/logstream-cep/logstream-cep.pid
        else
            echo "Error stopping logstream-cep"
        fi
        ;; 
  restart) 
        echo "Restarting logstream-cep"
        cat /opt/circonus/var/logstream-cep/logstream-cep.pid | xargs kill
        if [ 0 = $? ]; then
            rm /opt/circonus/var/logstream-cep/logstream-cep.pid
            /opt/circonus/bin/logstream-cep -P /opt/circonus/var/logstream-cep/logstream-cep.pid
        fi
        ;; 
  *) 
        echo "Usage: logstream-cep {start|stop|restart}" >&2 
        exit 3 
        ;; 
esac
